### ISSUE TITLE
Branch pre-release/1.0.0 does not compile On Ubuntu 24.04.3 LTS with gcc-13.3.0

### ISSUE THREAD

**Issue by Cr3sp1** [matteoilardi/Raytracer#17]
When trying to follow the instructions from the readme and running "make" I get the following compilation error:

[  3%] Building CXX object CMakeFiles/raytracer.dir/src/raytracer.cpp.o
In file included from /home/cristian/Downloads/C++/Raytracer/include/cameras.hpp:14,
                 from /home/cristian/Downloads/C++/Raytracer/include/materials.hpp:12,
                 from /home/cristian/Downloads/C++/Raytracer/include/renderers.hpp:12,
                 from /home/cristian/Downloads/C++/Raytracer/include/demo.hpp:15,
                 from /home/cristian/Downloads/C++/Raytracer/src/raytracer.cpp:3:
/home/cristian/Downloads/C++/Raytracer/include/random.hpp: In member function ‘float PCG::random_float()’:
/home/cristian/Downloads/C++/Raytracer/include/random.hpp:69:43: error: ‘powf’ is not a member of ‘std’; did you mean ‘pow’?
   69 |     return static_cast<float>(ran) / std::powf(2.f, 32);
      |                                           ^~~~
      |                                           pow
/home/cristian/Downloads/C++/Raytracer/include/random.hpp: In member function ‘std::pair<float, float> PCG::random_phong(int)’:
/home/cristian/Downloads/C++/Raytracer/include/random.hpp:78:24: error: ‘acosf’ is not a member of ‘std’; did you mean ‘acoshf’?
   78 |     float theta = std::acosf(std::powf(x, 1.f / (n + 1)));
      |                        ^~~~~
      |                        acoshf
/home/cristian/Downloads/C++/Raytracer/include/random.hpp:78:35: error: ‘powf’ is not a member of ‘std’; did you mean ‘pow’?
   78 |     float theta = std::acosf(std::powf(x, 1.f / (n + 1)));
      |                                   ^~~~
      |                                   pow
/home/cristian/Downloads/C++/Raytracer/include/renderers.hpp: In member function ‘virtual Color PointLightTracer::operator()(Ray) const’:
/home/cristian/Downloads/C++/Raytracer/include/renderers.hpp:162:72: error: ‘powf’ is not a member of ‘std’; did you mean ‘pow’?
  162 | at distance_factor = (source->emission_radius > 0.f) ? std::powf((source->emission_radius / distance), 2) : 1.f;
      |                                                             ^~~~
      |                                                             pow
make[2]: *** [CMakeFiles/raytracer.dir/build.make:76: CMakeFiles/raytracer.dir/src/raytracer.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:152: CMakeFiles/raytracer.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by matteoilardi** [comment]
Thanks for reaching out!

The issue is a C vs C++ standard mismatch.
Functions like powf, acosf, copysignf, etc. are actually C functions and are not guaranteed to exist in std::. The C++ standard instead provides overloaded functions in <cmath> (e.g. std::pow, std::acos) which correctly handle float, double, and long double.
